version: "3"
services:
    db_sgae:
        image: postgres:14-alpine3.15
        container_name: db-sgae
        environment:
            POSTGRES_USER: sgae_user
            POSTGRES_PASSWORD: abc123
            POSTGRES_DB: sgae
        volumes:
        - .:/db
        - ./db/postgres-data:/var/lib/postgresql/data
        ports:
        - 5432:5432
        restart: always

    web_sgae:
        container_name: web-sgae
        user: root
        build: .
        volumes:
            - "../:/var/www/html/"
            - ./php/php.ini:/usr/local/etc/php/php.ini
            - ./php/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf
            - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./supervisor/:/etc/supervisor/
        command: supervisord
        ports:
            - "80:80"
            - "9001:9001"
